# Generated by Django 4.2.4 on 2023-10-01 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SamsungApp', '0002_profile_delete_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celular',
            options={'ordering': ['usuario', '-fechaPublicacion']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fechaComentario']},
        ),
        migrations.AddField(
            model_name='celular',
            name='fechaPublicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='imagenCelular',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='celular',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='fechaComentario',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nombre',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
