# Generated by Django 4.2.4 on 2023-10-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamsungApp', '0003_alter_celular_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Post',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='celular',
            name='imagenCelular',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
