# Generated by Django 4.2.4 on 2023-10-04 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SamsungApp', '0004_rename_post_post_post_alter_celular_imagencelular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
