# Generated by Django 4.2.4 on 2023-10-09 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SamsungApp', '0005_alter_post_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celular',
            options={'ordering': ['-fechaPublicacion']},
        ),
        migrations.RemoveField(
            model_name='celular',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='celular',
            name='publicado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
